# Generated by Django 2.2.1 on 2020-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_registration_number',
            field=models.CharField(blank=True, default='', max_length=40, null=True, unique=True, verbose_name='user_registration_number'),
        ),
    ]
