# Generated by Django 2.2.1 on 2020-04-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='garbage',
        ),
        migrations.AddField(
            model_name='baseroute',
            name='garbage',
            field=models.ManyToManyField(to='master.Garbage', verbose_name='garbage'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_point', to='master.BaseRoute', verbose_name='route'),
        ),
    ]
