# Generated by Django 2.2.1 on 2020-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollectionpoint',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='address'),
        ),
    ]
