# Generated by Django 2.2.1 on 2020-04-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200407_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseroute',
            name='garbage',
        ),
        migrations.AddField(
            model_name='garbage',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garbage_collection_point', to='master.BaseRoute', verbose_name='route'),
        ),
    ]
