# Generated by Django 2.2.1 on 2020-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20200407_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='route',
        ),
        migrations.AddField(
            model_name='garbage',
            name='route',
            field=models.ManyToManyField(related_name='garbage', to='master.BaseRoute', verbose_name='route'),
        ),
    ]
