# Generated by Django 2.2.1 on 2020-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_collectionpoint_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollectionpoint',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='memo'),
        ),
    ]
