# Generated by Django 2.2.1 on 2020-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20200408_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='route',
        ),
        migrations.AddField(
            model_name='baseroute',
            name='garbage',
            field=models.ManyToManyField(related_name='route', to='master.Garbage', verbose_name='garbage'),
        ),
    ]
