# Generated by Django 2.2.1 on 2020-05-29 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20200408_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskroute',
            name='garbage',
            field=models.ManyToManyField(blank=True, to='master.Garbage', verbose_name='garbage'),
        ),
        migrations.AlterField(
            model_name='baseroute',
            name='garbage',
            field=models.ManyToManyField(blank=True, related_name='route', to='master.Garbage', verbose_name='garbage'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='collection_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_collection', to='master.TaskCollectionPoint', verbose_name='collection_point'),
        ),
        migrations.AlterField(
            model_name='taskcollectionpoint',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='0,0', max_length=63, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcollectionpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_collection_point', to='master.TaskRoute', verbose_name='route'),
        ),
    ]
