# Generated by Django 2.2.1 on 2020-07-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_taskcollectionpoint_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'ReportType',
                'verbose_name_plural': 'ReportTypes',
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('collection_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='master.CollectionPoint', verbose_name='collection_point')),
                ('report_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='master.ReportType', verbose_name='report_type')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='master.TaskRoute', verbose_name='route')),
            ],
            options={
                'verbose_name': 'TaskReport',
                'verbose_name_plural': 'TaskReports',
            },
        ),
    ]
