# Generated by Django 2.2.1 on 2020-07-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0006_reporttype_taskreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('garbage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount', to='master.Garbage', verbose_name='garbage')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount', to='master.TaskRoute', verbose_name='route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'TaskAmount',
                'verbose_name_plural': 'TaskAmounts',
            },
        ),
    ]
