# Generated by Django 2.2.1 on 2020-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20200603_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='timestamp',
            field=models.DateTimeField(default=0, verbose_name='timestamp'),
        ),
    ]
