# Generated by Django 2.2.1 on 2020-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20200604_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcollection',
            options={'verbose_name': 'TaskCollection', 'verbose_name_plural': 'TaskCollections'},
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True, verbose_name='timestamp'),
        ),
    ]
