# Generated by Django 2.2.1 on 2020-07-13 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20200713_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskamount',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='timestamp'),
        ),
    ]
