# Generated by Django 2.2.1 on 2020-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20200713_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskamount',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='taskroute',
            name='date',
            field=models.DateField(),
        ),
    ]
