# Generated by Django 2.2.1 on 2020-08-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20200713_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreport',
            name='collection_point',
        ),
        migrations.AddField(
            model_name='taskreport',
            name='task_collection_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='master.TaskCollectionPoint', verbose_name='task_collection_point'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_point', to='master.BaseRoute', verbose_name='route'),
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='collection_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_collection', to='master.TaskCollectionPoint', verbose_name='collection_point'),
        ),
        migrations.AlterField(
            model_name='taskcollectionpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_collection_point', to='master.TaskRoute', verbose_name='route'),
        ),
    ]
