# Generated by Django 2.2.1 on 2020-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20200604_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskroute',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=None, related_name='route', to='master.Vehicle', verbose_name='vehicle'),
        ),
    ]
