# Generated by Django 2.2.1 on 2020-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20200806_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseroute',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taskroute',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
