# Generated by Django 2.2.1 on 2020-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20200814_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='description'),
        ),
    ]
