# Generated by Django 2.2.1 on 2020-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_taskreport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskamount',
            name='memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='memo'),
        ),
    ]
