# Generated by Django 2.2.1 on 2020-12-03 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_taskamount_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskamount',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
