# Generated by Django 2.2.1 on 2020-12-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20201203_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
        migrations.AddField(
            model_name='taskamount',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ammount', to='master.Vehicle', verbose_name='vehicle'),
        ),
    ]
