# Generated by Django 2.2.1 on 2020-12-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20201203_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskamount',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='amount', to='master.Vehicle', verbose_name='vehicle'),
        ),
    ]
