# Generated by Django 3.2 on 2021-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20201208_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskroute',
            name='base_route_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='base_route_name'),
        ),
    ]
