# Generated by Django 3.2 on 2021-11-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20210504_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskamount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='taskamount',
            name='garbage',
        ),
        migrations.AddField(
            model_name='taskamount',
            name='deal_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='deal_type'),
        ),
        migrations.AddField(
            model_name='taskamount',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='work_type'),
        ),
        migrations.AlterField(
            model_name='taskamount',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount', to='master.taskroute'),
        ),
        migrations.CreateModel(
            name='TaskAmountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.IntegerField(default=0)),
                ('vehicle_weight', models.IntegerField(default=0)),
                ('garbage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_item', to='master.garbage', verbose_name='garbage')),
                ('task_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_item', to='master.taskamount', verbose_name='task_amount')),
            ],
            options={
                'verbose_name': 'TaskAmountItem',
                'verbose_name_plural': 'TaskAmountItems',
            },
        ),
    ]
